# Set this true if you want to load all the worlds at startup
# If it is false then you need to run the /loadall command
# You can only use true or false!
on startup:
- load-all: false
- exclude: 

on command:
- exclude: 
